### ISSUE TITLE
initialize repository with simple symfony 3.0 application

### ISSUE THREAD

**Issue by z-aliakseyeu** [nikolayhodosov/sf#1]
- [x] take install documentation from [symfony official page](http://symfony.com)
- [x] initialize repo from scratch
- [x] run app, make sure it works on your local machine

**Comment by nikolayhodosov** [comment]
![welcome to symfony jpg](https://cloud.githubusercontent.com/assets/18487077/14583487/ba9406c0-042b-11e6-9f6c-083b6d8eae34.jpg)

**Comment by z-aliakseyeu** [comment]
@nikolayhodosov you didn't push code to the repository! Please take of it today. That i will be able to see what are you working on in a real time.

**Comment by nikolayhodosov** [comment]
I am trying to understand what does it mean: push code to the repository. What code? Code - it is project on my computer and i need to connect my project with github ? or code it is something on programming language? I am reading and searching about it.. trying to uderstand
1 picture - i connect another project "mystpage" to github
2 picture - code of localhost:8000 from browser
![i connect another project "mystpage" to github](https://cloud.githubusercontent.com/assets/18487077/14608525/c49768e2-058e-11e6-8fb8-910a16ee1218.jpg)
![code of localhost 8000 from browser](https://cloud.githubusercontent.com/assets/18487077/14608530/c80f3a72-058e-11e6-85a4-fa3a5a6de73a.png)

**Comment by nikolayhodosov** [comment]
*_i connect another repository "mytestpage" to github
*_
![first commit](https://cloud.githubusercontent.com/assets/18487077/14611412/bd33e574-059a-11e6-8a5a-ede2dbc07bef.jpg)

**Comment by nikolayhodosov** [comment]
I did the same for "sf" repository (using terminal and PhpStorm)
![sf_project](https://cloud.githubusercontent.com/assets/18487077/14612720/5f654378-05a1-11e6-820a-a8065e9a42bb.jpg)

**Comment by z-aliakseyeu** [comment]
@nikolayhodosov pretty good. Now we can close this issue and you can move forward.
